name: nuconta_marketplace
description: A Flutter app where users spend their Nuconta balance on awesome products.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.10.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  graphql_flutter: 4.0.1
  bloc_pattern: 2.5.1
  rxdart: 0.24.0
  bloc_test: 7.1.0

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: 4.1.4
  network_image_mock: 1.1.0

flutter:
  uses-material-design: true
